### ISSUE TITLE
Fix 'Address already in use' error with TCP sockets

### ISSUE THREAD

**Issue by Totktonada** [tarantool/test-run#141]
TcpPortDispatcher was introduced to eliminate the race condition when two workers trying to use the same port: the idea is that each worker use its own ports range. Really these ports could race with client ports (from, say, net.box or replication), which typically don't use bind() and so binds to a random available port (despite any dispatched ranges). So this approach is broken by design.

There is the workaround with `use_unix_sockets` and `use_unix_sockets_iproto` options: setting them to `True` should eliminate the problem. However it is possible that some tests are designed to test tcp connections, so I think we should fix the problem.

The way I see is no-bind / bind to zero port and grep logs for a LISTEN / CONSOLE port (or write it from a script to a predefined location). Remove TcpPortDispatcher and find_port() at all.

Hmm, `box.cfg{listen = 0}` shows `binary: bound to 0.0.0.0:0`. Need to elaborate how to get the port.

The discussion had initially arisen in #115.

**Comment by Totktonada** [comment]
See https://github.com/tarantool/tarantool/issues/4620

**Comment by Totktonada** [comment]
Related: PR #210.

**Comment by sergos** [comment]
Hmm.. strange, for me it looks like `tarantool> box.cfg{listen=0}` yields `2022-02-16 01:07:32.744 [19216] main/103/interactive I> tx_binary: bound to [::]:53061` on MacOS and `2022-02-16 01:06:33.753 [10090] main/103/interactive I> tx_binary: bound to 0.0.0.0:36267` on Linux (Ubuntu 18.04)
The problem might be in the difference:
```
tarantool> box.cfg.listen
---
- 0
...

tarantool> box.info.listen
---
- '[::]:53061'
...

```

Anyways, letting the Tarantool instance to pick a port by itself looks way more robust, since no delay between assigning a port and binding it.

**Comment by Totktonada** [comment]
@sergos It is because https://github.com/tarantool/tarantool/issues/4620 was fixed. I filed this issue against tarantool specifically to have a change to use it here, in test-run.

**Comment by Totktonada** [comment]
Regarding 1.10, where we have no `box.info.listen`: https://github.com/tarantool/tt/pull/112#issuecomment-1209661575.

**Comment by NickZay** [comment]
I have some problems with ports when I use luatest with tarantool
