### ISSUE TITLE
Add memory usage profiling for running tests

### ISSUE THREAD

**Issue by avtikhon** [tarantool/test-run#277]
Need to add routines which will collect memory usage in runtime for tests. It is needed to resolve main issue
https://github.com/tarantool/tarantool-qa/issues/98

RSS memory usage file to parse:
/sys/fs/cgroup/memory/memory.limit_in_bytes

Style example of implementation:
https://github.com/tarantool/test-run/blob/5baa4f080dc82cd45bdc619743504a3c7203dd0d/lib/utils.py#L215-L233

**Comment by Totktonada** [comment]
I would highlight that we need to collect RSS per-test × per-configuration and do it always, not under an option. Othwerwise we'll not spot problematic tests.

Collecting just total RSS across the system does not work when we run several tests in parallel. It also don't work when you serve Web in a browser, while testing is going.

----

Regarding implementation. We need to track particular processes and use knowledge about a test name and configuration (BTW, we also can track a server name to spot which server consumes much memory). Python's Popen implementation does not save rusage: it uses waitpid(), not wait3() / wait4().  So we unable to catch a peak RSS after a process termination. Sadly, it is not reported in `/proc/<..pid..>/status` in `VmHWM` for a zombie process.

(Just raw idea: /usr/bin/time uses wait4() and can report peak RSS. Can we just wrap or subclass subprocess.Popen() with a wrapper that calls a necessary command under `/usr/bin/time -f %M <...>`, parses output and set it to a field in the process handler after the process termination? NB: Don't do that under --gdb, --lddb, --gdb-server, --valgrind, --strace.)

So we should collect RSS (`VmHWM` or `VmRSS` from `/proc/<..pid..>/status`) periodically. We can use `VmHWM` (maximum RSS) for app and unittest tests, but we should use `VmRSS` for tarantool tests, because the default server may be reused between several tests.

When a tarantool process is run, we should register it in a watcher with necessary metainformation: pid, suite, test name, configuration name, server name, some unique run identifier (see #255). The watcher should periodically collect information about registered processes. When a process is gone, unregister it (I guess we can assume that PIDs are rarely reused). After testing the collected information may be reported on the terminal. We can also write all collected samples into logs (to allow in-depth analysis).
