### ISSUE TITLE
Print reason of crash to .reject for tap tests

### ISSUE THREAD

**Issue by Korablev77** [tarantool/test-run#96]
Before this commit https://github.com/tarantool/test-run/commit/dac6b2b4640a7dd3d130ddde13bb4b25a730a4ad1 if sql-tap test crashed, the reason of crash (i.e. stack-trace or fired assertion) would be logged into *.reject file. It was great feature and I miss it so much. Moreover, it seems to be quite useful especially when executing test-run with force (--f) flag.

**Comment by Totktonada** [comment]
Another possible way to handle it: print last lines of a tarantool log (more then 15) right after last output when `--force` is enabled.

**Comment by Totktonada** [comment]
I think result/tmp_result/reject files are about stdout of a test and should not contain stderr/log.

We can introduce separate status file for failing tests that will contain a test output, stderr/logs and maybe other related info.

Another way is to show diff between result tmp_result (instead of result and reject) and make a reject file this status file.

Anyway, we need to reconsider stdout/stderr/logs handling at the whole and pay attention to TAP13 tests (#68).

**Comment by Totktonada** [comment]
I see no problems here now.

stderr is written to a separate file, which is shown on the screen, when a fail occurs.

If anyone experience problems with stderr, please, describe them as a user scenario and reopen the issue. I also suggest to wait for PR #394 first.
